language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - pylint clinic_app
  - coverage run -m unittest discover tests
  - coverage report

after_success:
  - coveralls